### PR TITLE
Add pre-commit hooks configuration

### LINKED ISSUE #193: Pre-commit hook configuration
It would be awesome to get out-of-the-box support for [pre-commit](https://pre-commit.com/) as plenty of other linters and auto-formatters such as flake8, pylint, black, or isort provide.

This is a matter of creating an appropriate `.pre-commit-hooks.yaml` file in the root of the repository as shown here: https://pre-commit.com/#new-hooks

### PR DESCRIPTION
**Pull request by jack1142**
## Summary

Fixes #193 
Since I'm not very familiar with how this tool works, I am unsure whether it is safe to run multiple Fixit processes (which is what pre-commit does by default by splitting out passed file names evenly) in parallel or if Fixit should be passed with all files at once. If it can cause some issues, I can add [`require_serial` option](https://pre-commit.com/#hooks-require_serial).

It would be great also to include this in the documentation though I don't know where you would want me to put it, it doesn't seem like there's any document related to integrations with IDEs and other tooling yet.

## Test Plan

1. Install pre-commit using:
```
python -m pip install pre-commit
```
2. Create a repository with a lint rule and autofixer to test on (I'm not familiar with this tool so I can't really give a specific example, I assume a reviewer will be able to come up with one)
3. Run pre-commit on all files to test the behavior of the hook:
```
pre-commit run --all-files
```

### CODE REVIEW

**Comment by zsol** [comment]
I think [this would be a great place](https://fixit.readthedocs.io/en/latest/getting_started.html#Enforcing-Custom-Rules) to add the docs (as a separate section)

**Comment by jack1142** [comment]
Alright, I'll try doing that today then.

About the failing checks, they are not related to this PR, seems like running CI on `main` *now* fails:
https://github.com/jack1142/Fixit/actions/runs/2324313329

**Comment by jack1142** [comment]
Took me 2 months to get to this but the documentation is now committed :)

**Comment by amyreese** [comment]
Hey there! We appreciate your contributions, but we're in the process of making some large changes to the core of Fixit. We will try to have more info about the direction we're heading soon, but in the mean time, we are closing all outstanding PR's from before we started this work. Thank you for your understanding.

**Comment by eggplants** [comment]
@Jackenmen Could you submit this PR again?

**Comment by amyreese** [comment]
@Jackenmen I'd be happy to review a PR adding precommit support (and appropriate docs) for the new, in-progress version so that it's available when we make a alpha/beta release in the near future. The CLI has changed, and the documentation has been completely redone, so it might be easier to make a new PR for that.

Docs for the upcoming version can be viewed at https://fixit.readthedocs.io/en/latest/

All that said, if you still believe this is useful for existing releases, we can reopen this PR and update it to apply to the `0.x` branch. Just be aware that we have no plans to make a new release from that branch.

**Pull request closed without merging**
