### PR TITLE
bump version to 0.1.2

### PR DESCRIPTION
**Pull request by zsol**

### CODE REVIEW

**Review by jimmylai — APPROVED** [review]
LGTM

**Comment by jimmylai** [comment]
There is one more merged PR that is not mentioned in the change set and it refactored UseAssertIsNotNoneRule using matcher to make it simpler.
https://github.com/Instagram/Fixit/commit/8a11a0969d943557c75a18438432975d4b4911db

**Comment by zsol** [comment]
I intentionally left that out because it seemed like an internal refactor that users wouldn't care much about. Do you think it should still be in the changelog?

**Comment by jimmylai** [comment]
> I intentionally left that out because it seemed like an internal refactor that users wouldn't care much about. Do you think it should still be in the changelog?

Make sense. I don't have strong preference.

**Pull request merged**
